name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm format:check
      - run: pnpm compile
      - run: pnpm build
        env:
          WXT_BACKEND_API_KEY: ${{ secrets.BACKEND_API_KEY }}
          WXT_BACKEND_URL: ${{ secrets.BACKEND_URL }}
      - run: pnpm build:firefox
        env:
          WXT_BACKEND_API_KEY: ${{ secrets.BACKEND_API_KEY }}
          WXT_BACKEND_URL: ${{ secrets.BACKEND_URL }}
